version: '3'
services:
    postgres:
      container_name: postgres
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_DB: "ski"
        POSTGRES_USER: "ski"
        POSTGRES_PASSWORD: "ski"
    ski-app:
      container_name: ski-app
      build: .
      image: ski-image
      ports:
      - "11099:11099"
      environment:
        POSTGRES_HOST: "postgres:5432"
        POSTGRES_DB: "ski"
      depends_on:
      - postgres